name: Generate Python Client from OpenAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-SFTPgo-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install openapi-python-client
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if OpenAPI Spec Exists
        run: |
          if [ ! -f openapi.yaml ]; then
            echo "❌ openapi.yaml not found!"
            exit 1
          fi

      - name: Generate Python Client
        run: |
          rm -rf SFTPgo-client
          openapi-python-client generate --path openapi.yaml --output-path SFTPgo-client

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add SFTPgo-client
          git commit -m "chore: update Python client from OpenAPI spec" 
          git diff --cached --quiet || (git commit -m "chore: update Python client from OpenAPI spec" && git push origin main)